language: python
# well its really octave, but that is not supported
#

sudo: false

#addons:
#  apt:
#    sources:
#    - ppa:octave/stable

addons:
  apt:
    packages:
    - octave
    - liboctave-dev

matrix:
  include:
    - python: "2.7"
      env: SYMPY_VER=0.7.5 DOCTEST=no
    - python: "2.7"
      env: SYMPY_VER=0.7.6 DOCTEST=yes
    - python: "3.4"
      env: SYMPY_VER=0.7.6 DOCTEST=yes

# need octave devel pkgs for doctest (has compiled code as of July 2015)
install:
  - "pip install sympy==$SYMPY_VER"
  - octave --eval "pkg install -forge doctest"

# all commands here must have exit code 0 for the build to be called "passing"
# debugging: octave --eval "syms x; A = [x sin(x) x^3]; A; exit(0)"
script:
  - octave --eval "ver; pwd; exit(0)"
  - pushd src; make; popd
  - pushd inst
  - octave --eval "r = octsympy_tests; exit(r)"
  - cat octsympy_tests.log
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave --eval "pkg load doctest; syms x; r = doctest('.'); exit(~r)";
    fi
  - popd

#after_script:
#  - echo ${TRAVIS_TEST_RESULT}
